### ISSUE TITLE
Evaluation interval in MT10/MT50 benchmarks for multi-task RL

### ISSUE THREAD

**Issue by heshandevaka** [Cranial-XIX/CAGrad#5]
Hi, Thank you for sharing this resource and congratulations on the great work!
I have some issue regarding the logs generated by the MT10/MT50 benchmarks for multi-task RL. The paper suggest that the agent is evaluated every 10,000 training steps, but the log files only show evaluation results every 30,000 training steps, after implementing the MT10 benchmark following the given instructions for the setup. Is this expected? In that case is there a way to retrieve evaluation results every 10,000 steps, as described in the paper? If not, have I missed something in the setup or is there any configuration I need to change in order to rectify this issue? 
Thanks in advance for the consideration!

**Comment by Cranial-XIX** [comment]
Hi, thanks! I think you can modify the eval frequency in the mtrl config file [here](https://github.com/facebookresearch/mtrl/blob/b6db5d8c1a273cc38ffd8613a70ad54426806dae/config/experiment/mtrl.yaml#L7) .
But I think the default eval frequency is indeed 10,000 training steps (Maybe you can make sure you are on the right commit).

**Comment by heshandevaka** [comment]
Thank you for the quick response!
The eval frequency is set to 10,000 in my local repo, similar to your reference. But still log files have evaluations at 30,000 steps.  I noticed that there are 150 steps per episode, which suggest that some evaluations episodes have to be run before finishing a training episode (since 10,000 is not a multiple of 150). I am wandering whether this is the issue. Is this the correct number of steps used in the original implementation? I could not see a config option to set the steps per episode.

**Comment by Cranial-XIX** [comment]
Hi, I started a quick a run and it does seem that what you mentioned is the issue. So even if we set ```eva_freq``` to 10,000, since [here](https://github.com/facebookresearch/mtrl/blob/b6db5d8c1a273cc38ffd8613a70ad54426806dae/mtrl/experiment/multitask.py#L179) the evaluation happens inside an if-statement where step has to be a multiple of ```max_episode_steps```, the actual evaluation interval will be 30,000. Sorry that in the paper we just report the config parameter we set, but in actual implementation it is indeed 30,000 steps per evaluation because of mtrl's implementation. You could set the ```max_episode_steps``` to 100, but that might influence the final evaluation, so I would suggest not doing that.

**Comment by heshandevaka** [comment]
Hi, thanks again for the quick response, and thanks for the clarification! 
Yes, I think that makes a lot of sense. And yes, changing the per episode number of steps will affect the evaluation. I will look into further whether I can avoid this while having an evaluation frequency of 10,000. But I will close this issue, since my original concern was clarified. Thanks again for your time!
